packages:
  - configs/*
  - core/*
  - infra/*
  - web/*

catalog:
  '@vitest/coverage-v8': ^4.0.18
  '@vue/test-utils': ^2.4.6
  jsdom: ^27.4.0
  pathe: ^2.0.3
  unbuild: 3.6.1
  vitest: ^4.0.18
  '@vitest/ui': ^4.0.18
  vue: ^3.5.26
