packages:
  - configs/*
  - core/*
  - infra/*
  - web/*

catalog:
  '@vitest/coverage-v8': ^4.0.6
  '@vue/test-utils': ^2.4.6
  jsdom: ^27.0.1
  pathe: ^2.0.3
  unbuild: 3.6.1
  vitest: ^4.0.6
  '@vitest/ui': ^4.0.6
  vue: ^3.5.22
