packages:
  - configs/*
  - core/*
  - infra/*
  - web/*

catalog:
  '@vitest/coverage-v8': ^3.2.4
  '@vue/test-utils': ^2.4.6
  jsdom: ^26.1.0
  pathe: ^2.0.3
  unbuild: 3.6.1
  vitest: ^3.2.4
  '@vitest/ui': ^3.2.4
  vue: ^3.5.19
