packages:
  - configs/*
  - core/*
  - infra/*
  - web/*

catalog:
  '@vitest/coverage-v8': ^3.1.3
  '@vue/test-utils': ^2.4.6
  jsdom: ^26.1.0
  pathe: ^2.0.3
  unbuild: 3.5.0
  vitest: ^3.1.3
  '@vitest/ui': ^3.1.3
  vue: ^3.5.14
