packages:
  - configs/*
  - core/*
  - infra/*
  - web/*
  - docs

catalog:
  '@vitest/coverage-v8': ^4.1.4
  '@vue/test-utils': ^2.4.6
  jsdom: ^29.0.2
  oxlint: ^1.59.0
  tsdown: ^0.21.7
  vitest: ^4.1.4
  '@vitest/ui': ^4.1.4
  vue: ^3.5.32
  nuxt: ^4.4.2
