/**
 * Phone-number formats for every country: an international template with the
 * dialing-code digits as `#` digit placeholders, plus the `priority`/`areaCodes`
 * used to disambiguate countries sharing a dialing code (NANP `+1`, `+7` RU/KZ).
 * NANP territories are normalized to code `'1'` (their 3-digit prefix moved into
 * `areaCodes`), so every dialing code is prefix-free and the `+1` block shares one
 * numbering-plan template. Derived from the MIT-licensed `react-phone-input-2`
 * dataset — display formats, not authoritative validation.
 */

/**
 * One country's phone-number format.
 */
export interface PhoneCountry {
  /** Display name, e.g. `'United States'` (omit for custom lists). */
  readonly name?: string;
  /** ISO 3166-1 alpha-2 code, lowercase, e.g. `'us'` (omit for custom lists). */
  readonly iso2?: string;
  /** International dialing code digits (no `+`), e.g. `'1'`, `'380'`. */
  readonly code: string;
  /** International template; `#` is a digit, e.g. `'+# (###) ###-####'`. */
  readonly template: string;
  /**
   * Order among countries sharing `code` — lower wins when no area code matches.
   * Absent means `0` (the primary country for that code).
   */
  readonly priority?: number;
  /** Area codes (the digits right after `code`) that belong to this country. */
  readonly areaCodes?: readonly string[];
}

/**
 * Every supported country. Resolve a number with `findPhoneCountry`.
 */
export const PHONE_COUNTRIES: readonly PhoneCountry[] = [
  { name: 'Afghanistan', iso2: 'af', code: '93', template: '+## #############' },
  { name: 'Albania', iso2: 'al', code: '355', template: '+### ############' },
  { name: 'Algeria', iso2: 'dz', code: '213', template: '+### ############' },
  { name: 'Andorra', iso2: 'ad', code: '376', template: '+### ############' },
  { name: 'Angola', iso2: 'ao', code: '244', template: '+### ############' },
  { name: 'Antigua and Barbuda', iso2: 'ag', code: '1', template: '+# (###) ###-####', priority: 10, areaCodes: ['268'] },
  { name: 'Argentina', iso2: 'ar', code: '54', template: '+## (##) ########' },
  { name: 'Armenia', iso2: 'am', code: '374', template: '+### ## ######' },
  { name: 'Aruba', iso2: 'aw', code: '297', template: '+### ############' },
  { name: 'Australia', iso2: 'au', code: '61', template: '+## (##) #### ####' },
  { name: 'Austria', iso2: 'at', code: '43', template: '+## #############' },
  { name: 'Azerbaijan', iso2: 'az', code: '994', template: '+### (##) ### ## ##' },
  { name: 'Bahamas', iso2: 'bs', code: '1', template: '+# (###) ###-####', priority: 10, areaCodes: ['242'] },
  { name: 'Bahrain', iso2: 'bh', code: '973', template: '+### ############' },
  { name: 'Bangladesh', iso2: 'bd', code: '880', template: '+### ############' },
  { name: 'Barbados', iso2: 'bb', code: '1', template: '+# (###) ###-####', priority: 10, areaCodes: ['246'] },
  { name: 'Belarus', iso2: 'by', code: '375', template: '+### (##) ### ## ##' },
  { name: 'Belgium', iso2: 'be', code: '32', template: '+## ### ## ## ##' },
  { name: 'Belize', iso2: 'bz', code: '501', template: '+### ############' },
  { name: 'Benin', iso2: 'bj', code: '229', template: '+### ############' },
  { name: 'Bhutan', iso2: 'bt', code: '975', template: '+### ############' },
  { name: 'Bolivia', iso2: 'bo', code: '591', template: '+### ############' },
  { name: 'Bosnia and Herzegovina', iso2: 'ba', code: '387', template: '+### ############' },
  { name: 'Botswana', iso2: 'bw', code: '267', template: '+### ############' },
  { name: 'Brazil', iso2: 'br', code: '55', template: '+## (##) #########' },
  { name: 'British Indian Ocean Territory', iso2: 'io', code: '246', template: '+### ############' },
  { name: 'Brunei', iso2: 'bn', code: '673', template: '+### ############' },
  { name: 'Bulgaria', iso2: 'bg', code: '359', template: '+### ############' },
  { name: 'Burkina Faso', iso2: 'bf', code: '226', template: '+### ############' },
  { name: 'Burundi', iso2: 'bi', code: '257', template: '+### ############' },
  { name: 'Cambodia', iso2: 'kh', code: '855', template: '+### ############' },
  { name: 'Cameroon', iso2: 'cm', code: '237', template: '+### ############' },
  { name: 'Canada', iso2: 'ca', code: '1', template: '+# (###) ###-####', priority: 1, areaCodes: ['204', '226', '236', '249', '250', '289', '306', '343', '365', '387', '403', '416', '418', '431', '437', '438', '450', '506', '514', '519', '548', '579', '581', '587', '604', '613', '639', '647', '672', '705', '709', '742', '778', '780', '782', '807', '819', '825', '867', '873', '902', '905'] },
  { name: 'Cape Verde', iso2: 'cv', code: '238', template: '+### ############' },
  { name: 'Caribbean Netherlands', iso2: 'bq', code: '599', template: '+### ############', priority: 1 },
  { name: 'Central African Republic', iso2: 'cf', code: '236', template: '+### ############' },
  { name: 'Chad', iso2: 'td', code: '235', template: '+### ############' },
  { name: 'Chile', iso2: 'cl', code: '56', template: '+## #############' },
  { name: 'China', iso2: 'cn', code: '86', template: '+## ##-#########' },
  { name: 'Colombia', iso2: 'co', code: '57', template: '+## ### ### ####' },
  { name: 'Comoros', iso2: 'km', code: '269', template: '+### ############' },
  { name: 'Congo', iso2: 'cd', code: '243', template: '+### ############' },
  { name: 'Congo', iso2: 'cg', code: '242', template: '+### ############' },
  { name: 'Costa Rica', iso2: 'cr', code: '506', template: '+### ####-####' },
  { name: 'Côte d’Ivoire', iso2: 'ci', code: '225', template: '+### ## ## ## ##' },
  { name: 'Croatia', iso2: 'hr', code: '385', template: '+### ############' },
  { name: 'Cuba', iso2: 'cu', code: '53', template: '+## #############' },
  { name: 'Curaçao', iso2: 'cw', code: '599', template: '+### ############' },
  { name: 'Cyprus', iso2: 'cy', code: '357', template: '+### ## ######' },
  { name: 'Czech Republic', iso2: 'cz', code: '420', template: '+### ### ### ###' },
  { name: 'Denmark', iso2: 'dk', code: '45', template: '+## ## ## ## ##' },
  { name: 'Djibouti', iso2: 'dj', code: '253', template: '+### ############' },
  { name: 'Dominica', iso2: 'dm', code: '1', template: '+# (###) ###-####', priority: 10, areaCodes: ['767'] },
  { name: 'Dominican Republic', iso2: 'do', code: '1', template: '+# (###) ###-####', priority: 2, areaCodes: ['809', '829', '849'] },
  { name: 'Ecuador', iso2: 'ec', code: '593', template: '+### ############' },
  { name: 'Egypt', iso2: 'eg', code: '20', template: '+## #############' },
  { name: 'El Salvador', iso2: 'sv', code: '503', template: '+### ####-####' },
  { name: 'Equatorial Guinea', iso2: 'gq', code: '240', template: '+### ############' },
  { name: 'Eritrea', iso2: 'er', code: '291', template: '+### ############' },
  { name: 'Estonia', iso2: 'ee', code: '372', template: '+### #### ######' },
  { name: 'Ethiopia', iso2: 'et', code: '251', template: '+### ############' },
  { name: 'Fiji', iso2: 'fj', code: '679', template: '+### ############' },
  { name: 'Finland', iso2: 'fi', code: '358', template: '+### ## ### ## ##' },
  { name: 'France', iso2: 'fr', code: '33', template: '+## # ## ## ## ##' },
  { name: 'French Guiana', iso2: 'gf', code: '594', template: '+### ############' },
  { name: 'French Polynesia', iso2: 'pf', code: '689', template: '+### ############' },
  { name: 'Gabon', iso2: 'ga', code: '241', template: '+### ############' },
  { name: 'Gambia', iso2: 'gm', code: '220', template: '+### ############' },
  { name: 'Georgia', iso2: 'ge', code: '995', template: '+### ############' },
  { name: 'Germany', iso2: 'de', code: '49', template: '+## #### ########' },
  { name: 'Ghana', iso2: 'gh', code: '233', template: '+### ############' },
  { name: 'Greece', iso2: 'gr', code: '30', template: '+## #############' },
  { name: 'Grenada', iso2: 'gd', code: '1', template: '+# (###) ###-####', priority: 10, areaCodes: ['473'] },
  { name: 'Guadeloupe', iso2: 'gp', code: '590', template: '+### ############' },
  { name: 'Guam', iso2: 'gu', code: '1', template: '+# (###) ###-####', priority: 10, areaCodes: ['671'] },
  { name: 'Guatemala', iso2: 'gt', code: '502', template: '+### ####-####' },
  { name: 'Guinea', iso2: 'gn', code: '224', template: '+### ############' },
  { name: 'Guinea-Bissau', iso2: 'gw', code: '245', template: '+### ############' },
  { name: 'Guyana', iso2: 'gy', code: '592', template: '+### ############' },
  { name: 'Haiti', iso2: 'ht', code: '509', template: '+### ####-####' },
  { name: 'Honduras', iso2: 'hn', code: '504', template: '+### ############' },
  { name: 'Hong Kong', iso2: 'hk', code: '852', template: '+### #### ####' },
  { name: 'Hungary', iso2: 'hu', code: '36', template: '+## #############' },
  { name: 'Iceland', iso2: 'is', code: '354', template: '+### ### ####' },
  { name: 'India', iso2: 'in', code: '91', template: '+## #####-#####' },
  { name: 'Indonesia', iso2: 'id', code: '62', template: '+## #############' },
  { name: 'Iran', iso2: 'ir', code: '98', template: '+## ### ### ####' },
  { name: 'Iraq', iso2: 'iq', code: '964', template: '+### ############' },
  { name: 'Ireland', iso2: 'ie', code: '353', template: '+### ## #######' },
  { name: 'Israel', iso2: 'il', code: '972', template: '+### ### ### ####' },
  { name: 'Italy', iso2: 'it', code: '39', template: '+## ### #######' },
  { name: 'Jamaica', iso2: 'jm', code: '1', template: '+# (###) ###-####', priority: 10, areaCodes: ['876'] },
  { name: 'Japan', iso2: 'jp', code: '81', template: '+## ## #### ####' },
  { name: 'Jordan', iso2: 'jo', code: '962', template: '+### ############' },
  { name: 'Kazakhstan', iso2: 'kz', code: '7', template: '+# (###) ###-##-##', priority: 1, areaCodes: ['310', '311', '312', '313', '315', '318', '321', '324', '325', '326', '327', '336', '7172', '73622'] },
  { name: 'Kenya', iso2: 'ke', code: '254', template: '+### ############' },
  { name: 'Kiribati', iso2: 'ki', code: '686', template: '+### ############' },
  { name: 'Kosovo', iso2: 'xk', code: '383', template: '+### ############' },
  { name: 'Kuwait', iso2: 'kw', code: '965', template: '+### ############' },
  { name: 'Kyrgyzstan', iso2: 'kg', code: '996', template: '+### ### ### ###' },
  { name: 'Laos', iso2: 'la', code: '856', template: '+### ############' },
  { name: 'Latvia', iso2: 'lv', code: '371', template: '+### ## ### ###' },
  { name: 'Lebanon', iso2: 'lb', code: '961', template: '+### ############' },
  { name: 'Lesotho', iso2: 'ls', code: '266', template: '+### ############' },
  { name: 'Liberia', iso2: 'lr', code: '231', template: '+### ############' },
  { name: 'Libya', iso2: 'ly', code: '218', template: '+### ############' },
  { name: 'Liechtenstein', iso2: 'li', code: '423', template: '+### ############' },
  { name: 'Lithuania', iso2: 'lt', code: '370', template: '+### ############' },
  { name: 'Luxembourg', iso2: 'lu', code: '352', template: '+### ############' },
  { name: 'Macau', iso2: 'mo', code: '853', template: '+### ############' },
  { name: 'Macedonia', iso2: 'mk', code: '389', template: '+### ############' },
  { name: 'Madagascar', iso2: 'mg', code: '261', template: '+### ############' },
  { name: 'Malawi', iso2: 'mw', code: '265', template: '+### ############' },
  { name: 'Malaysia', iso2: 'my', code: '60', template: '+## ##-####-####' },
  { name: 'Maldives', iso2: 'mv', code: '960', template: '+### ############' },
  { name: 'Mali', iso2: 'ml', code: '223', template: '+### ############' },
  { name: 'Malta', iso2: 'mt', code: '356', template: '+### ############' },
  { name: 'Marshall Islands', iso2: 'mh', code: '692', template: '+### ############' },
  { name: 'Martinique', iso2: 'mq', code: '596', template: '+### ############' },
  { name: 'Mauritania', iso2: 'mr', code: '222', template: '+### ############' },
  { name: 'Mauritius', iso2: 'mu', code: '230', template: '+### ############' },
  { name: 'Mexico', iso2: 'mx', code: '52', template: '+## ### ### ####' },
  { name: 'Micronesia', iso2: 'fm', code: '691', template: '+### ############' },
  { name: 'Moldova', iso2: 'md', code: '373', template: '+### (##) ##-##-##' },
  { name: 'Monaco', iso2: 'mc', code: '377', template: '+### ############' },
  { name: 'Mongolia', iso2: 'mn', code: '976', template: '+### ############' },
  { name: 'Montenegro', iso2: 'me', code: '382', template: '+### ############' },
  { name: 'Morocco', iso2: 'ma', code: '212', template: '+### ############' },
  { name: 'Mozambique', iso2: 'mz', code: '258', template: '+### ############' },
  { name: 'Myanmar', iso2: 'mm', code: '95', template: '+## #############' },
  { name: 'Namibia', iso2: 'na', code: '264', template: '+### ############' },
  { name: 'Nauru', iso2: 'nr', code: '674', template: '+### ############' },
  { name: 'Nepal', iso2: 'np', code: '977', template: '+### ############' },
  { name: 'Netherlands', iso2: 'nl', code: '31', template: '+## ## ########' },
  { name: 'New Caledonia', iso2: 'nc', code: '687', template: '+### ############' },
  { name: 'New Zealand', iso2: 'nz', code: '64', template: '+## ###-###-####' },
  { name: 'Nicaragua', iso2: 'ni', code: '505', template: '+### ############' },
  { name: 'Niger', iso2: 'ne', code: '227', template: '+### ############' },
  { name: 'Nigeria', iso2: 'ng', code: '234', template: '+### ############' },
  { name: 'North Korea', iso2: 'kp', code: '850', template: '+### ############' },
  { name: 'Norway', iso2: 'no', code: '47', template: '+## ### ## ###' },
  { name: 'Oman', iso2: 'om', code: '968', template: '+### ############' },
  { name: 'Pakistan', iso2: 'pk', code: '92', template: '+## ###-#######' },
  { name: 'Palau', iso2: 'pw', code: '680', template: '+### ############' },
  { name: 'Palestine', iso2: 'ps', code: '970', template: '+### ############' },
  { name: 'Panama', iso2: 'pa', code: '507', template: '+### ############' },
  { name: 'Papua New Guinea', iso2: 'pg', code: '675', template: '+### ############' },
  { name: 'Paraguay', iso2: 'py', code: '595', template: '+### ############' },
  { name: 'Peru', iso2: 'pe', code: '51', template: '+## #############' },
  { name: 'Philippines', iso2: 'ph', code: '63', template: '+## #### #######' },
  { name: 'Poland', iso2: 'pl', code: '48', template: '+## ###-###-###' },
  { name: 'Portugal', iso2: 'pt', code: '351', template: '+### ############' },
  { name: 'Puerto Rico', iso2: 'pr', code: '1', template: '+# (###) ###-####', priority: 3, areaCodes: ['787', '939'] },
  { name: 'Qatar', iso2: 'qa', code: '974', template: '+### ############' },
  { name: 'Réunion', iso2: 're', code: '262', template: '+### ############' },
  { name: 'Romania', iso2: 'ro', code: '40', template: '+## #############' },
  { name: 'Russia', iso2: 'ru', code: '7', template: '+# (###) ###-##-##' },
  { name: 'Rwanda', iso2: 'rw', code: '250', template: '+### ############' },
  { name: 'Saint Kitts and Nevis', iso2: 'kn', code: '1', template: '+# (###) ###-####', priority: 10, areaCodes: ['869'] },
  { name: 'Saint Lucia', iso2: 'lc', code: '1', template: '+# (###) ###-####', priority: 10, areaCodes: ['758'] },
  { name: 'Saint Vincent and the Grenadines', iso2: 'vc', code: '1', template: '+# (###) ###-####', priority: 10, areaCodes: ['784'] },
  { name: 'Samoa', iso2: 'ws', code: '685', template: '+### ############' },
  { name: 'San Marino', iso2: 'sm', code: '378', template: '+### ############' },
  { name: 'São Tomé and Príncipe', iso2: 'st', code: '239', template: '+### ############' },
  { name: 'Saudi Arabia', iso2: 'sa', code: '966', template: '+### ############' },
  { name: 'Senegal', iso2: 'sn', code: '221', template: '+### ############' },
  { name: 'Serbia', iso2: 'rs', code: '381', template: '+### ############' },
  { name: 'Seychelles', iso2: 'sc', code: '248', template: '+### ############' },
  { name: 'Sierra Leone', iso2: 'sl', code: '232', template: '+### ############' },
  { name: 'Singapore', iso2: 'sg', code: '65', template: '+## ####-####' },
  { name: 'Slovakia', iso2: 'sk', code: '421', template: '+### ############' },
  { name: 'Slovenia', iso2: 'si', code: '386', template: '+### ############' },
  { name: 'Solomon Islands', iso2: 'sb', code: '677', template: '+### ############' },
  { name: 'Somalia', iso2: 'so', code: '252', template: '+### ############' },
  { name: 'South Africa', iso2: 'za', code: '27', template: '+## #############' },
  { name: 'South Korea', iso2: 'kr', code: '82', template: '+## ### #### ####' },
  { name: 'South Sudan', iso2: 'ss', code: '211', template: '+### ############' },
  { name: 'Spain', iso2: 'es', code: '34', template: '+## ### ### ###' },
  { name: 'Sri Lanka', iso2: 'lk', code: '94', template: '+## #############' },
  { name: 'Sudan', iso2: 'sd', code: '249', template: '+### ############' },
  { name: 'Suriname', iso2: 'sr', code: '597', template: '+### ############' },
  { name: 'Swaziland', iso2: 'sz', code: '268', template: '+### ############' },
  { name: 'Sweden', iso2: 'se', code: '46', template: '+## (###) ###-###' },
  { name: 'Switzerland', iso2: 'ch', code: '41', template: '+## ## ### ## ##' },
  { name: 'Syria', iso2: 'sy', code: '963', template: '+### ############' },
  { name: 'Taiwan', iso2: 'tw', code: '886', template: '+### ############' },
  { name: 'Tajikistan', iso2: 'tj', code: '992', template: '+### ############' },
  { name: 'Tanzania', iso2: 'tz', code: '255', template: '+### ############' },
  { name: 'Thailand', iso2: 'th', code: '66', template: '+## #############' },
  { name: 'Timor-Leste', iso2: 'tl', code: '670', template: '+### ############' },
  { name: 'Togo', iso2: 'tg', code: '228', template: '+### ############' },
  { name: 'Tonga', iso2: 'to', code: '676', template: '+### ############' },
  { name: 'Trinidad and Tobago', iso2: 'tt', code: '1', template: '+# (###) ###-####', priority: 10, areaCodes: ['868'] },
  { name: 'Tunisia', iso2: 'tn', code: '216', template: '+### ############' },
  { name: 'Turkey', iso2: 'tr', code: '90', template: '+## ### ### ## ##' },
  { name: 'Turkmenistan', iso2: 'tm', code: '993', template: '+### ############' },
  { name: 'Tuvalu', iso2: 'tv', code: '688', template: '+### ############' },
  { name: 'Uganda', iso2: 'ug', code: '256', template: '+### ############' },
  { name: 'Ukraine', iso2: 'ua', code: '380', template: '+### (##) ### ## ##' },
  { name: 'United Arab Emirates', iso2: 'ae', code: '971', template: '+### ############' },
  { name: 'United Kingdom', iso2: 'gb', code: '44', template: '+## #### ######' },
  { name: 'United States', iso2: 'us', code: '1', template: '+# (###) ###-####' },
  { name: 'Uruguay', iso2: 'uy', code: '598', template: '+### ############' },
  { name: 'Uzbekistan', iso2: 'uz', code: '998', template: '+### ## ### ## ##' },
  { name: 'Vanuatu', iso2: 'vu', code: '678', template: '+### ############' },
  { name: 'Vatican City', iso2: 'va', code: '39', template: '+## ### #######', priority: 1 },
  { name: 'Venezuela', iso2: 've', code: '58', template: '+## #############' },
  { name: 'Vietnam', iso2: 'vn', code: '84', template: '+## #############' },
  { name: 'Yemen', iso2: 'ye', code: '967', template: '+### ############' },
  { name: 'Zambia', iso2: 'zm', code: '260', template: '+### ############' },
  { name: 'Zimbabwe', iso2: 'zw', code: '263', template: '+### ############' },
];
