name: CI

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Test
        run: pnpm test